### ISSUE TITLE
Set logging timezone

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#13]
Hi,

Is it possible to set the operation logging timezone as the machines time, or user specified in the config.json? e.g. using the  tz database `Country/City`.

Right now it is set to UTC

Thanks!

**Comment by w0d4** [comment]
Hi,

logging timezone is always system timezone.
It would be possible to change that, but this would require some dependencies to more packages.
I have one machine with UTC and one with CEST.
The one with UTC logs in UTC, the one with CEST logs in CEST.
I also looked to my code again and couldn't find any part where timezone is set to UTC.
So, I assume it's always the system time.

**Comment by sideloading** [comment]
Thanks for the clarification, it was indeed my system time that was set to UTC 🤦‍♂️
