### ISSUE TITLE
[Grafana] Overview dashboard ask for table that doesn't exist/

### ISSUE THREAD

**Issue by Zulux91** [w0d4/yt-backup#16]
I have fully configured the dashboards for Grafana and all of them are working as expected except for the portion that shows "Videos downloaded per day". It [asks for a table that doesn't exist](https://imgur.com/a/fBFAD1d). As far as I can tell table creation is being managed by the script.

**Comment by w0d4** [comment]
I missed the third view you need.
I added it in the readme: https://github.com/w0d4/yt-backup#mysqlmariadb

**Comment by Zulux91** [comment]
Thank you. It's working perfectly now! :D
