### ISSUE TITLE
yt-backup doesn't handle quota exceeded message

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#19]
**Describe the bug**
I receive a traceback error once exceeding Google's API quota.

**To Reproduce**
Run `yt-backup.py run` until you reach quota.

**Expected behavior**
To catch the error message, possibly pause the `run` utility till another 12-24 hrs?

**Debug log**
This is the systemd logs, as I had it running as a service named `archive.service`
```bash
May 20 06:00:09 ubuntu python3[119715]: 2020-05-20 06:00:09,884 - yt-backup - INFO - Getting Playlists for ASMR Vilma [UC_XcqkoxMMHA6qAqUFMlgDA]
May 20 06:00:10 ubuntu python3[119715]: Traceback (most recent call last):
May 20 06:00:10 ubuntu python3[119715]:   File "/mnt/shares/yt-backup/yt-backup.py", line 1157, in <module>
May 20 06:00:10 ubuntu python3[119715]:     get_playlists()
May 20 06:00:10 ubuntu python3[119715]:   File "/mnt/shares/yt-backup/yt-backup.py", line 463, in get_playlists
May 20 06:00:10 ubuntu python3[119715]:     get_channel_playlists(channel.channel_id)
May 20 06:00:10 ubuntu python3[119715]:   File "/mnt/shares/yt-backup/yt-backup.py", line 294, in get_channel_playlists
May 20 06:00:10 ubuntu python3[119715]:     google_response = get_playlist_ids_from_google(local_channel_id)
May 20 06:00:10 ubuntu python3[119715]:   File "/mnt/shares/yt-backup/yt-backup.py", line 246, in get_playlist_ids_from_google
May 20 06:00:10 ubuntu python3[119715]:     response = request.execute()
May 20 06:00:10 ubuntu python3[119715]:   File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
May 20 06:00:10 ubuntu python3[119715]:     return wrapped(*args, **kwargs)
May 20 06:00:10 ubuntu python3[119715]:   File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/googleapiclient/http.py", line 907, in execute
May 20 06:00:10 ubuntu python3[119715]:     raise HttpError(resp, content, uri=self.uri)
May 20 06:00:10 ubuntu python3[119715]: googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id=UC_XcqkoxMMHA6qAqUFMlgDA&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.">
May 20 06:00:10 ubuntu systemd[1]: archive.service: Main process exited, code=exited, status=1/FAILURE
May 20 06:00:10 ubuntu systemd[1]: archive.service: Failed with result 'exit-code'.
May 20 06:00:10 ubuntu systemd[1]: Failed to start yt-backup download.
```

**Additional context**
n/a

**Comment by w0d4** [comment]
Just out of intereset. How often do you execute the run and how many channels do you monitor?
I have never exceeded my quota, even with all the development tests.

**Comment by w0d4** [comment]
I have pushed commit 8eafb7c for this.
Disclaimer: I have not tested this, since I will not exceed my quota for testing :-D

**Comment by sideloading** [comment]
>How often do you execute the run and how many channels do you monitor?

I have about 460 channels added currently, and had it running in 3 hr intervals as a test run. I definitely need to re-calculate the cost for doing an entire run... LOL. Previously, I've had a bash script with those 460 channels checking 15-30 mins with youtube-dl with no issues.

>I have pushed commit 8eafb7c for this.

Thanks! Will keep monitoring the logs for any issues.

**Comment by w0d4** [comment]
OK, 460 channels every 3 hours will kill the quota for sure.
Your bash script with youtube-dl worked, since i assume it was not using youtube API, but plain youtube-dl.
Youtube-dl hast the problem with 429 gate, since every video of every channel is called once before checking archive.list. This was my initial reason to write this.
I have around 30 channels with 27k videos in them and i run into 429 HTTP error every day.

**Comment by sideloading** [comment]
The only time I've received the 429 error was on a VPS which has considerably faster bandwidth compared to the bash script which is on my home network.. I haven't encountered it yet otherwise. I am using `--sleep-interval 60` as a measure, but who knows.

I did a single run and it seems to have costed 966/10,000.

I will close this issue, thanks!

**Comment by w0d4** [comment]
I have pushed a new version. I added some kind of quota monitoring. I hope I got this right.
You can now add the --print_quota flag to every command, to see how much quota each operation will cost and get a summary at the and.
I also updated the grafana dashboard to show the quota used in the last 24h
