### ISSUE TITLE
Traceback error when adding non-existent channel

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#27]
**Describe the bug**
When adding a non-existent channel, you receive a traceback error.

**To Reproduce**
Add a nonexistent channel e.g.
`python yt-backup.py add_channel --channel_id asdf-00000`

**Expected behavior**
Catch the error and exit.

**Debug log**
```
Traceback (most recent call last):
  File "yt-backup.py", line 1578, in <module>
    add_channel(channel_id)
  File "yt-backup.py", line 494, in add_channel
    channel_name = get_channel_name_from_google(local_channel_id)
  File "yt-backup.py", line 448, in get_channel_name_from_google
    channel_name = str(response["items"][0]["brandingSettings"]["channel"]["title"])
KeyError: 'items'
```

**Additional context**

**Comment by w0d4** [comment]
This is fixed in latest release.
