### ISSUE TITLE
[Feature] Enable/disable channel using --channel_id parameter

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#33]
Currently the command to enable/disable the channel is the following:
`python3 yt-backup.py toggle_channel_download --username <channel_name> --enable/disable` 

It would be nice to enable/disable by simply using the channel_id.
e.g. `python3 yt-backup.py toggle_channel_download --channel_id <channel_id> --enable/disable`

**Comment by w0d4** [comment]
Implemented in 25180c0

**Comment by sideloading** [comment]
Thanks!

**Comment by sideloading** [comment]
hey @w0d4, I'm not sure if it's working correctly. Running the command does not output anything like it would, and the download requirement stays the same.

Running the following command: `python3 yt-backup.py toggle_channel_download --channel_id "channel_ID" --disable`

let me know if you need me to test further!
