### ISSUE TITLE
Age gated videos will not be downloaded

### ISSUE THREAD

**Issue by w0d4** [w0d4/yt-backup#35]
**Describe the bug**
Videos with special content will not be donwloaded when not logged in.
Message: This video may be inappropriate for some users. Sign in to confirm your age.

**To Reproduce**
Download video wk0HZEZLcnM without being logged in.

**Expected behavior**
Download the video anyways.

**Comment by coletdjnz** [comment]
youtube-dl issue, requires a manual youtube-dl patch for now - https://github.com/ytdl-org/youtube-dl/pull/26100

**Comment by sideloading** [comment]
This should be fixed now with youtube-dl v2020.09.06 https://github.com/ytdl-org/youtube-dl/releases/tag/2020.09.06

**Comment by w0d4** [comment]
Yes, this is fixed now in youtube-dl
