### ISSUE TITLE
yt-backup won't run:  Missing dependencies for SOCKS support, SOCKS5 server installed.

### ISSUE THREAD

**Issue by Jugrnot** [w0d4/yt-backup#41]
Have been working on this for almost a month now off and on when I have time.  Finally managed to get the application "installed" and configured, added a single video to download, but I just can't make this thing work.  OS is Ubuntu 18LTS in a Proxmox LXC.  Instructions didn't mention anything about the requirement of a SOCKS server, but I have installed one.  I have danted socks5 sever installed and configured for user auth and I added that to the yt-backup config.json, receive the output below.  Removed user based authentication on danted, receive the exact same output below.  Tested danted SOCKS5 proxy with curl and confirmed it works.  Completely stuck.

> Jugrnot@YoutubeDL:~/yt-backup$ python3 yt-backup.py run
> 2020-07-03 00:19:22,876 - yt-backup - INFO - Verifying channel status against youtube API for all channels
> 2020-07-03 00:19:23,798 - yt-backup - INFO - Updating online status of all channels.
> 2020-07-03 00:19:23,803 - yt-backup - INFO - 0 playlists changed.
> Traceback (most recent call last):
>   File "yt-backup.py", line 1660, in <module>
>     download_videos()
>   File "yt-backup.py", line 901, in download_videos
>     current_country = get_current_country()
>   File "yt-backup.py", line 1055, in get_current_country
>     r = requests.get("https://ipinfo.io", proxies=proxies)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
>     return request('get', url, params=params, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 412, in send
>     conn = self.get_connection(request.url, proxies)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 309, in get_connection
>     proxy_manager = self.proxy_manager_for(proxy)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 189, in proxy_manager_for
>     **proxy_kwargs
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 47, in SOCKSProxyManager
>     raise InvalidSchema("Missing dependencies for SOCKS support.")
> requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

I googled this:  requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
Got the idea in the config.json to change socks5: to http: or https: and receive this for the output for both:

> Jugrnot@YoutubeDL:~/yt-backup$ python3 yt-backup.py run
> 2020-07-03 00:25:01,855 - yt-backup - INFO - Verifying channel status against youtube API for all channels
> 2020-07-03 00:25:02,682 - yt-backup - INFO - Updating online status of all channels.
> 2020-07-03 00:25:02,688 - yt-backup - INFO - 0 playlists changed.
> 2020-07-03 00:25:02,695 - yt-backup - ERROR - Cannot get connection to ipinfo.io
> 2020-07-03 00:25:02,699 - yt-backup - INFO - I have 1 in download queue. Start downloading now.
> 2020-07-03 00:25:02,755 - yt-backup - INFO - Video NdDulJw2Gkk - Working On The TOTALED Kia Is More DIFFICULT Than You THINK *Airbag Computer Removal* is not yet downloaded. Downloading now.
> 2020-07-03 00:25:03,080 - yt-backup - INFO - Verifying offline video IDs against youtube API
> 2020-07-03 00:25:03,083 - yt-backup - INFO - Getting rclone size of complete archive dir
> Traceback (most recent call last):
>   File "yt-backup.py", line 1662, in <module>
>     generate_statistics(True)
>   File "yt-backup.py", line 1081, in generate_statistics
>     size_json = json.loads(stdout)
>   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>

**Comment by Jugrnot** [comment]
Is this project still alive??

**Comment by w0d4** [comment]
Hi, yes project is alive.
In general, you don't need a socks server.
If you don't want to use a proxy, just leave the "proxy" config value empty.
May you post an anonymized version of your config.json? 
Would you also please post the output of a run with the --debug flag?

**Comment by Jugrnot** [comment]
Holy crap, I didn't even think to try a --debug flag.  Managed to get the proxy issue fixed as you suggested just leaving blank and turns out I somehow had the wrong path for rclone binary in the config.json which I completely glossed over.

Haven't had a ton of time to mess with this over the last week, but it's successfully downloaded the one single video I added to the database, so far as this particular issue goes I'm good.

One question / possible request:  Are there any other useful flags that might not be documented in the wiki similar to --debug?  If so, would you mind adding a brief section of those to the wiki?  Thanks for your help with this!

**Comment by w0d4** [comment]
Nice to hear it's working for you now.
Thanks for the hint, that --debug ist not in the README.
If you want to have an overview of all options, you can always run `python3 yt-backup.py --help`
Nearly everything is printed there. Only some internal options I had for my special case are not documented.
