### ISSUE TITLE
[Request] Channel country metadata

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#47]
It would be great to get the country assigned to channels, which can then be used with Grafana's Worldmap plugin. 

It is under brandingSettings>country in the API

**Comment by w0d4** [comment]
I will look how to integrate this.
The good thing is, while adding new channels, there is already an API call for brandingSettings
The problem will be, that I need to change the data model. So we have to migrate it to the new data model.
Also I need a way to add all missing countries from existing channels to the database. This could cause issues with API quotas on larger databases.

**Comment by w0d4** [comment]
Hi @sideloading ,
I have created a new branch, which implements channel countries. https://github.com/w0d4/yt-backup/tree/channel_countries
Please checkout the branch and test it.
I have tested it with my main database with around 120 channels in it.
Please make sure, you have a current backup of your database. Your data model will be migrated to model version 4. You cannot switch back to master branch without going back to your database backup.
At the first start during the migration of database model, all channels without country information will be queried against the youtube API. This costs 3 quotas for every 50 channels in your DB.
During my test, I found out, that there are channels on youtube, which do not provide country information in their channel.
I have not started anything with grafana until now.

**Comment by w0d4** [comment]
I have fiddled around a bit with the grafana world map feature. It seems to work.
As input to grafana world map feature, I use the following SQL statement:
`SELECT channel_country, COUNT(*) FROM `channels` WHERE channel_country IS NOT NULL GROUP BY channel_country`
This produces the following view
![screenshot](https://user-images.githubusercontent.com/64585757/144215614-2eb98290-c579-434c-94ce-d7b1874b5d14.png)

**Comment by sideloading** [comment]
@w0d4 Long overdue but thank you so much! This is great 🥳

**Comment by sideloading** [comment]
@w0d4 Would you have the json export for the panel? I can't seem to get the data to display 😅

**Comment by w0d4** [comment]
Hi, I have added the panel json to the project for you.
https://github.com/w0d4/yt-backup/blob/master/grafana-dashboards/yt-backup%20-%20country%20data%20panel.json

**Comment by sideloading** [comment]
Thank you @w0d4  🙏
