### ISSUE TITLE
Google OAuth2 OOB Error

### ISSUE THREAD

**Issue by oneandonlyjason** [w0d4/yt-backup#55]
**Describe the bug**
Google changed the OAuth2 Flow and now no Connection to the YT Data APIs is working

When you try to Authorize the OAuth Token you get a Application Blocked Error

**Comment by sideloading** [comment]
Can you try the workaround written in #52?

**Comment by oneandonlyjason** [comment]
I tried the Workaround but then get this Error when i Access the URL it prints on Console:

device_id and device_name are required for private IP

**Comment by oneandonlyjason** [comment]
My Headless Machine has no Public IP which Probably is the Problem here

**Comment by oneandonlyjason** [comment]
I now just generated the needed File on another Device with Display and Copied it to the Headless Device
