### ISSUE TITLE
Import already downloaded videos/channels

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#7]
Mentioned in the to-do list, creating issue to track it.

User *jdphoto77* has a similar archiving set up, with an ingest script for existing videos, could aid with implementation https://github.com/jdphoto77/yt_archive/blob/master/ingest_vids.sh

**Comment by Zulux91** [comment]
Just point `"download-archive": "/home/user/archive.list"` in your config.json to your already existing `--download-archive` youtubedl file.

**Comment by sideloading** [comment]
@Zulux91 sure, that's one way of doing it, but this won't import any data/statistics to the database.

**Comment by w0d4** [comment]
I marked it as anhancement, since there is already some feature to import already downloaded videos. I agree, that some other feature to get statistics of already existing files would be nice to see. But this is not highest priority on my list.

**Comment by w0d4** [comment]
I have released the add_video mode in commit 7976fab0f6e73c53da8be71f568d65ea04cde039
This could be used to build a custom import wrapper around the script as a workaround for now.
**Warning:** Each added video will be looked up against youtube API. This could use your API quota really quickly.
I think this is the best solution for now. Also solution of jdphoto77 only works for one specific naming convention. I don't think I can release something in the near future to support ALL possible naming solutions.

**Comment by sideloading** [comment]
Thanks, that is helpful.

@w0d4 are you able to add an optional `--title` flag as well?

**Comment by w0d4** [comment]
Title will be pulled from YouTube api.
You want to be able to set a different title by hand?

**Comment by sideloading** [comment]
Yes, that would be great - since there is always a possibility of a video being removed.

**Comment by w0d4** [comment]
Since this is working now and it's not possible to have an universal import script for all formats, I will close this.
