### ISSUE TITLE
Youtube-DL HTTP Error stops the Script

### ISSUE THREAD

**Issue by oneandonlyjason** [w0d4/yt-backup#8]
I just had the same error again as in #4 and thought I found an error with MP4 files again. So I started the download again with the --Debug option and found the following YT-DL error. `yt-backup - DEBUG - Current line: [download]   0.5% of 21.83MiB at 777.60KiB/                                     s ETA 00:28[download] Got server HTTP error: Downloaded 110316 bytes, expected 22895270 bytes. Retrying                                      (attempt 1 of 10)...
2020-05-11 13:07:38,044 - yt-backup - DEBUG - Current line:
2020-05-11 13:07:38,044 - yt-backup - DEBUG - Current line:
` I searched a bit in the internet and found a YTDL Github bug [report](https://github.com/ytdl-org/youtube-dl/issues/14845) that Youtube returns a wrong size for some videos and you should choose another format for this one video. It doesn't look like the Youtube download developers are willing to fix this.  So I would suggest that YT-Backup catches this error if possible and simply excludes the video from the download. Currently it just crashes and leaves the lock file and pieces of the video on the hard disk.

**Comment by w0d4** [comment]
Yes, the video should get flagged with an error and the script should continue. If you don't mind, share the video ID privately again. I have never seen a video where this happens.

**Comment by oneandonlyjason** [comment]
Send it on Reddit

**Comment by w0d4** [comment]
Pushed 0c325773da997cdb21fee60d353f6172822ba99e
Should fix this problem.

**Comment by oneandonlyjason** [comment]
Seems to work

**Comment by oneandonlyjason** [comment]
But what I just saw is that he tries to download the video again on the next run. He should completely ignore videos with this error, because otherwise more and more video will accumulate over time and take up unnecessary runtime because he tries it again and again.

**Comment by w0d4** [comment]
Yes, this was a bug in the code. Is fixed now in 3c10fa63d0eff27fc6d8071f0e582d9ad989f4de
If you want to retry forbidden and failed videos, you can add --retry-403 to your download_videos or run mode flags
