### ISSUE TITLE
Add videos by title and description. Also offline videos.

### ISSUE THREAD

**Issue by w0d4** [w0d4/yt-backup#9]
add an optional `--title` flag when adding videos.
Add the possibility to add already offline videos

_Originally posted by @bpo5r5 in https://github.com/w0d4/yt-backup/issues/7#issuecomment-627990237_

**Comment by w0d4** [comment]
I pushed 26f3b739dab9f3e11eb0e260ffd13c7d367af16f
You CAN now add --video_title and --video_description
If video is offline on youtube a user MUST add --video_title, --video_description and --playlist_id
If a user defines --video_status offline the youtube API will not be queried for the video to save API Quota.

@bpo5r5 Test it if you want to

**Comment by sideloading** [comment]
Thanks for the quick implementation!
I have all the metadata.jsons available, now is the task of scripting it 😄

**Comment by w0d4** [comment]
I assume this is working now for you.
